### ISSUE TITLE
Strange failure with a Rails 8 app

### ISSUE THREAD

**Issue by zerobearing2** [PNixx/clickhouse-activerecord#185]
Trying to configure a secondary database to clickhouse. Getting a strange error after installing the gem and configuring the database.yml.

database.yml
```yaml
development:
  primary:
    ...
  clickhouse:
    adapter: clickhouse
    database: default
    host: localhost
    port: 8123
    database_tasks: false
```

Rails console:
```ruby
app(dev)> User.first
(app):1:in `<main>': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
```

Without the gem installed, this AR loads just fine. 
```ruby
app(dev)> User.first
  User Load (0.6ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> 
#<User:0x000073476e0a2fe8
 id: "05ab38c7-7008-4fc2-b68e-6e5c49d9c4ca",
 email: "[FILTERED]",
 ...>
```

Is Rails 8 support planned soon-ish? Would like to test drive clickhouse with our Rails app.
