### ISSUE TITLE
You have N pending migrations

### ISSUE THREAD

**Issue by FlintOFF** [PNixx/clickhouse-activerecord#195]
Hello
I have two DB's, the first one is PostgreSQL, and the second one is Clickhouse.
I updated `Rails` from 7.0.8.7 to 7.2.2.1 and `clickhouse-activerecord` from 0.6.2 to 1.3.0.
Now I trying to call the `bin/rails db:seed` command but receive the next error message "You have N pending migrations".
I found that adding `migrations_paths: db/migrate_clickhouse` into `database.yml` resolved the issue, but according to README.md the config is optional and has the same default value as my path to clickhouse's migrations (`migrations_paths: db/clickhouse # optional, default: db/migrate_clickhouse`).
Could you please tell me is it an outdated README.md file or something else?

**Comment by PNixx** [comment]
Write your example `database.yml`

**Comment by FlintOFF** [comment]
Before (with pending migrations issue)

```yml
default: &default
  primary: &primary
    adapter: postgresql
    encoding: unicode
    host: <%= ENV["DB_HOST"] || "localhost" %>
    username: <%= ENV["DB_USERNAME"] || "root" %>
    password: <%= ENV["DB_PASSWORD"] || "" %>
    pool: 5
  clickhouse: &clickhouse
    adapter: clickhouse
    host: <%= ENV["CLICKHOUSE_HOST"] || "localhost" %>
    database: <%= ENV["CLICKHOUSE_DATABASE"] || "clickhouse" %>
    user: <%= ENV["CLICKHOUSE_USER"] || "default" %>
    password: <%= ENV["CLICKHOUSE_PASSWORD"] || "" %>

development: &development
  primary:
    <<: *primary
    database: <%= ENV["CYPRESS"] ? "test" : "development" %>
  clickhouse:
    <<: *clickhouse
    database: clickhouse_dev

test:
  primary:
    <<: *primary
    database: test
    min_messages: WARNING
  clickhouse:
    <<: *clickhouse
    database: clickhouse_test

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
  clickhouse:
    <<: *clickhouse
```

After (without issue)
```yml
default: &default
  primary: &primary
    adapter: postgresql
    encoding: unicode
    host: <%= ENV["DB_HOST"] || "localhost" %>
    username: <%= ENV["DB_USERNAME"] || "root" %>
    password: <%= ENV["DB_PASSWORD"] || "" %>
    pool: 5
  clickhouse: &clickhouse
    adapter: clickhouse
    host: <%= ENV["CLICKHOUSE_HOST"] || "localhost" %>
    database: <%= ENV["CLICKHOUSE_DATABASE"] || "clickhouse" %>
    user: <%= ENV["CLICKHOUSE_USER"] || "default" %>
    password: <%= ENV["CLICKHOUSE_PASSWORD"] || "" %>
    migrations_paths: db/migrate_clickhouse


development: &development
  primary:
    <<: *primary
    database: <%= ENV["CYPRESS"] ? "test" : "development" %>
  clickhouse:
    <<: *clickhouse
    database: clickhouse_dev

test:
  primary:
    <<: *primary
    database: test
    min_messages: WARNING
  clickhouse:
    <<: *clickhouse
    database: clickhouse_test

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
  clickhouse:
    <<: *clickhouse
```
