### ISSUE TITLE
Undefined method configured_migrate_path in migration

### ISSUE THREAD

**Issue by r72cccp** [PNixx/clickhouse-activerecord#31]
Hello, i'm try to write my first migration, but receive next error:
```bash
rails g clickhouse_migration create_table_company name:string
```
=>
```
.rvm/gems/ruby-2.6.5/gems/clickhouse-activerecord-0.3.12/lib/generators/clickhouse_migration_generator.rb:16:in `db_migrate_path': undefined local variable or method `configured_migrate_path' for #<ClickhouseMigrationGenerator:0x000055df8dcd7b30> (NameError)
```

I'm sure, that all setting from readme is correct:
database.yml:
```yml
development_clickhouse:
  adapter: clickhouse
  host: localhost
  port: 8123
  debug: true
  migrations_paths: db/migrate_clickhouse
  username: clickhouse
  password: clickhouse
```

With best regards!
