### ISSUE TITLE
Option for Pool

### ISSUE THREAD

**Issue by eni9889** [PNixx/clickhouse-activerecord#33]
I am getting the following error:

```
could not obtain a connection from the pool within 5.000 seconds
```

Is there an option to set a pool param or is this in the works?

**Comment by PNixx** [comment]
This is error from pool rails. You need set pool connections greater or equal your workers.
```
production:
  adapter: clickhouse
  pool: 50
  ***
```
