### ISSUE TITLE
How can I deploy app using this and clickhouse to heroku?

### ISSUE THREAD

**Issue by jawadakram20** [PNixx/clickhouse-activerecord#53]

**Comment by PNixx** [comment]
Please describe your problem in more detail.

**Comment by benschwarz** [comment]
@PNixx On Heroku databases are configured using environment variable `DATABASE_URL`, which means it's often used within `database.yml` like this:

```
production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["MAX_THREADS"] || 5 %>
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || "30s" %>
```

I guess what @jawadakram20 is looking for is a connection string similar to how it would be done with Postgres:

```
DATABASE_URL=postgres://{user}:{password}@{hostname}:{port}/{database-name}
```
