### ISSUE TITLE
Cannot run migrations with multiple databases

### ISSUE THREAD

**Issue by eni9889** [PNixx/clickhouse-activerecord#64]
Hi,

I am getting the following error:
```
ActiveRecord::AdapterNotSpecified: The `development_clickhouse` database is not configured for the `development` environment.
```

When running 
```
bundle exec rake clickhouse:migrate
```

This is my database.yml
```
default: &default
  statistics:
    adapter: clickhouse
    database: statistics
    user: <%= ENV.fetch("DB_USER") { "default" }%>
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT") { "8123" }%>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i + 2 %>
    password: <%= ENV["DB_PASSWORD"] %>
    migrations_paths: db/statistics_migrate

  analytics:
    adapter: clickhouse
    database: analytics
    user: <%= ENV.fetch("DB_USER") { "default" }%>
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT") { "8123" }%>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i + 2 %>
    password: <%= ENV["DB_PASSWORD"] %>
    migrations_paths: db/analytics_migrate

development:
  <<: *default
```

If I run
```
bundle exec rake clickhouse:prepare_schema_migration_table
bundle exec rake clickhouse:prepare_internal_metadata_table
bundle exec rake db:migrate
```

I get

```
rake aborted!
ActiveRecord::StatementInvalid: ActiveRecord::ActiveRecordError: Response code: 404:
Code: 47, e.displayText() = DB::Exception: There's no column 'schema_migrations.active' in table 'schema_migrations' (version 20.8.7.15 (official build))
/Users/egjoka/.asdf/installs/ruby/2.6.6/bin/bundle:23:in `load'
/Users/egjoka/.asdf/installs/ruby/2.6.6/bin/bundle:23:in `<main>'

```
